---
# tasks file for jenkins
- include_role:
    name: oracle-java

- name: Install python-pycurl
  yum: name=python-pycurl state=installed

- name: Import jenkins key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
    validate_certs: no

- name: Get jenkins repo for ansible
  yum_repository:
    name: jenkins
    state: present
    description: Official Jenkins Yum Repo
    baseurl: http://pkg.jenkins.io/redhat
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: yes
    enabled: yes

- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
  register: jenkins_install

- name: Create jenkins configuration
  file:
    path: /etc/sysconfig/jenkins
    state: touch

- name: Configure Jenkins Port
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_PORT=
    line: JENKINS_PORT={{jenkins_port}}
  register: config_changed

- name: Configure Jenkins for $JAVA_HOME
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_JAVA_CMD=
    line: JENKINS_JAVA_CMD="{{ java_home }}/bin/java"
  register: config_changed

- name: Configure Jenkins Prefix
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_ARGS=
    line: JENKINS_ARGS={{prefix}}
  when: prefix is defined
  register: config_changed
#
#- name: Add jenkins user into sudoers for sudo access
#  lineinfile:
#    dest: /etc/sudoers
#    line: "{{ item.line }}"
#    create: yes
#    state: present
#  with_items:
#    - { line: 'jenkins  ALL=(ALL)   NOPASSWD: ALL' }
#    - { line: 'Defaults:jenkins !requiretty' }

- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Ensure wheel group has passwordless sudo - create sudoers.d file
  copy:
    dest: /etc/sudoers.d/10_wheel
    content: '%wheel ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440

- name: Add jenkins user to wheel group
  user:
    name: jenkins
    groups: wheel
    append: yes
    shell: /bin/bash

- name: Restart jenkins now
  service: name=jenkins state=restarted enabled=yes
  when: config_changed.changed

