version: '3'
services:
  web:
#    build: .
#    ports:
#      - "5000:5000"
#  redis:
#    image: "redis:alpine"
#  web:
#    #    image: "127.0.0.1:5001/web-app:latest"
#    #    ports:
#    #      - "5000:80"
    image: "127.0.0.1:5001/web-app:latest"
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"