- hosts: all
  become: true
  roles:
    - docker
    - git
#    - jenkins
    - prometheus
    - node-exporter
    - role: grafana
      vars:
        grafana_security:
          admin_user: "admin"
          admin_password: "admin"
